language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
install:
- NODE_ENV=development npm install
before_script:
- npm run lint
script:
- npm run test:coverage
after_script:
- npm run test:report
deploy:
  provider: npm
  email: npm@devlato.com
  api_key:
    secure: a263++vv2y+KdN6lZdxyogFB6worQ1u0vwu9f9yg/UbLtVY6R5NEYbuxvOr6XIAR8urOBXQ7/oogD/n1XLw0OvdRAyFRte3D8YRRZDfhbeX6cYQq9/o8SczPH3Lb8ph5ZEW2sumTIse2G+cGeGH3TkDaQCfUHs8Md8m+NzpD4mrQ5MKy+fqJHvN04fb5sEQGbSZx16JJ9aCxYMOez02nlbW81r24HQABSR98oVmkv7AHsISJ+z4wcVPTwt0SvCGoW/1up4GYzk0/Sp0At0isvFZgQCXxC9Nsce7UX0L3L1BqDA+eu+nOgtphYebnfqMOILFNMi+CAe017dpkER3LHn2f/HrMoJKTa2AAshKZPm6Q7PQbyDth4UjARKKdZ3q3yWuHqTJLOVmR7bsjT9CcK8L911mjfdK8UC/ANzLsZdIsn6lrMc4Y8Z1eqIy06OImXunqzusXUT04Y5PztdrgMj6Nesur3ZJovn63cGlWBoLBk9vfU/LYI9SluiFS4K79xBGiTKnqw4+4yc1ReStzzxO2WWD10glcW0b7miHj7ygng7JqZAs52nAMHF5a7z8soFxPKUExfhluGpJbFXzMCsKvV8ct9slDad4Lf1Wwb4DPV64M8YXkwLXeUA/vRAY10KHOGsPaZaJwzuiy7fPcFgYQ7hsrw4p3mzfUnvqz+gY=
  on:
    tags: true
    repo: devlato/react-goatse
